# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site Settings
title: "GDG DevFest Season 2014"
email: "gdg@gdgyarmouk.com"
description: "GDG DevFest is a set of events all around the world"
baseurl: "/testgdg2"
url: "http://gdg-x.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"

# Organizer Info
organizerName: "GDG Yarmouk"
organizerAlternateName: "Google Developer Group Yarmouk"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "gdg@gdgyarmouk.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, yarmouk"
twitterAccount: "@gdgyarmouk"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
bottomNavigationLinks:
 - {link: "http://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "http://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG DevFest<typeout>2014"
eventDate: "September 27, 2014"
typeoutTextValues: '"", "Season", "Yarmouk", "Jordan", "With Zain"'
typeoutFallback: "Season"
heroButtons:
 - {link: "http://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "find tickets"}

# About Block
aboutTitle: "About GDG DevFest"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lot's of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day free-style hackaton! Want some real teambuilding on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Zain Jordan HQ"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "Jordan, Amman , 8th Circle"
eventAddressLocality: "Zain"
eventAddressLocalityRegion: "Lvivska"
eventPostalCode: "79000"
eventAddressCountry: "Ukraine"
eventStartTime: "2014-09-27T09:00"
eventDoorTime: "08:00"
eventEndTime: "2014-29-27T19:00"
eventPlaceCoordinates: "31.963299, 35.844601"
mapCenterCoordinates: "31.963299, 35.844601"
mapMobileCenterCoordinates: "31.963299, 35.844601"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Normal Tickets"
  price: "00"
  priceCurrency: "JOD"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "https://docs.google.com/forms/d/1wAQMPLzcje7TkPuZdRC73DdUpAOIqiu0PpZ7Bo7lUYI/viewform"
  buyButtonText: "Take it Now"
  ticketContentList: ["Students", "Developers", "Employees"]
  validFrom: "2014-09-01T10:00"
  validThrough: "2014-09-27T23:59"
 -
  name: "Last Chance"
  price: "00"
  priceCurrency: "JOD"
  ticketsNumber: "100"
  ribbon: "100%"
  featured: true
  buyButtonLink: "https://docs.google.com/forms/d/1wAQMPLzcje7TkPuZdRC73DdUpAOIqiu0PpZ7Bo7lUYI/viewform"
  buyButtonText: "Take it Now"
  ticketContentList: ["For last chance", "in last weeks", "wait us"]
  validFrom: "2014-09-20T00:00"
  validThrough: "2014-09-27T23:59"
  disabled: true
 -
  name: "Press"
  price: "00"
  priceCurrency: "JOD"
  ticketsNumber: "50"
  buyButtonLink: "https://docs.google.com/forms/d/1wAQMPLzcje7TkPuZdRC73DdUpAOIqiu0PpZ7Bo7lUYI/viewform"
  buyButtonText: "Take it Now"
  additionalInfo: "Only for press stuffs, to make a reports for GDG DevFest 2014"
  ticketContentList: ["TV", "Newspapers", "Radio"]
  validFrom: "2014-09-01T10:00"
  validThrough: "2014-09-26T23:59"

# Footer
socialLinks:
 - {link: "https://plus.google.com/105734230312112352829", icon: "google-plus"}
 - {link: "https://twitter.com/gdgyarmouk", icon: "twitter"}
 - {link: "https://www.facebook.com/GDGYarmouk", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdg.org.ua", text: "GDG Yarmouk"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:gdg@yarmouk.com", text: "gdg@yarmouk.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfesYarmouk"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "31.963299, 35.844601"
logisticsMapMobileCenterCoordinates: "31.963299, 35.844601"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Yarmouk"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards: 
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   - 
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didnâ€™t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
